import { db } from '@/lib/db'

/**
 * Simulated GitHub Actions runner (sandbox preview).
 * Streams realistic build logs into the DB, then finalizes with artifacts.
 * On a real GitHub push, the included workflow produces the genuine APK.
 */

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))

const stamp = () => new Date().toISOString().replace('T', ' ').slice(0, 19)

function buildLogLines(appName: string, repoName: string, commitSha: string): string[] {
  return [
    `[${stamp()}] [queue] Waiting for a runner to pick up this job...`,
    `[queue] Job assigned: ubuntu-latest (runner 2vcpu-7gb)`,
    ``,
    `##[group]Run actions/checkout@v4`,
    `Syncing repository: ${repoName}`,
    `> git fetch --depth=1 origin main`,
    `> git checkout main`,
    `HEAD is now at ${commitSha.slice(0, 7)} Initial commit — generated by BuildAI 🤖`,
    `##[endgroup]`,
    ``,
    `##[group]Run actions/setup-java@v4`,
    `Resolving Java version '17' from distribution 'temurin'`,
    `Installed: Eclipse Temurin 17.0.11+9 (x86_64-linux)`,
    `##[endgroup]`,
    ``,
    `##[group]Run gradle/actions/setup-gradle@v3`,
    `Downloading Gradle 8.7 distribution...`,
    `Gradle 8.7 installed ✓`,
    `##[endgroup]`,
    ``,
    `##[group]Run chmod +x gradlew`,
    `##[endgroup]`,
    ``,
    `##[group]Run ./gradlew assembleDebug --no-daemon`,
    `Starting a Gradle Daemon (subsequent builds will be faster)`,
    `> Task :app:preBuild UP-TO-DATE`,
    `> Task :app:preDebugBuild UP-TO-DATE`,
    `> Task :app:mergeDebugResources`,
    `> Task :app:compileDebugJavaWithJavac`,
    `note: Processing R.java for ${appName}...`,
    `> Task :app:processDebugManifest`,
    `> Task :app:dexBuilderDebug`,
    `> Task :app:mergeDebugJavaResource`,
    `> Task :app:mergeDexDebug`,
    `> Task :app:packageDebug`,
    `> Task :app:assembleDebug`,
    `BUILD SUCCESSFUL in 14s`,
    `7 actionable tasks: 7 executed`,
    `##[endgroup]`,
    ``,
    `##[group]Run actions/upload-artifact@v4`,
    `Uploading: app/build/outputs/apk/debug/app-debug.apk`,
    `Artifact app-debug-apk uploaded ✓`,
    `##[endgroup]`,
    ``,
    `✅ Job succeeded — APK is ready under Artifacts`,
  ]
}

export function startBuild(buildId: string, projectId: string) {
  // Fire-and-forget async pipeline; DB polling serves progress to the client.
  ;(async () => {
    try {
      const project = await db.project.findUnique({ where: { id: projectId } })
      if (!project) return

      const lines = buildLogLines(project.appName, project.repoName || project.name, 'gen' + Math.random().toString(36).slice(2, 9))
      let elapsedStart = Date.now()

      await db.build.update({ where: { id: buildId }, data: { status: 'running' } })

      for (let i = 0; i < lines.length; i++) {
        await sleep(220 + Math.random() * 260)
        const partial = lines.slice(0, i + 1).join('\n')
        await db.build.update({
          where: { id: buildId },
          data: { logs: partial },
        })
      }

      const duration = Math.round((Date.now() - elapsedStart) / 1000)
      await db.build.update({
        where: { id: buildId },
        data: {
          status: 'success',
          commitSha: 'sha' + Math.random().toString(36).slice(2, 9),
          apkName: 'app-debug.apk',
          apkSize: `${(2.1 + Math.random() * 1.4).toFixed(1)} MB`,
          duration,
          completedAt: new Date(),
        },
      })
      await db.project.update({
        where: { id: projectId },
        data: { status: 'built' },
      })
    } catch (err) {
      await db.build
        .update({
          where: { id: buildId },
          data: {
            status: 'failed',
            logs: (err instanceof Error ? err.message : String(err)) + '\n',
            completedAt: new Date(),
          },
        })
        .catch(() => {})
    }
  })()
}

