import { NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { getSessionUser } from '@/lib/auth'
import { pushProjectToGitHub } from '@/lib/github'

export const dynamic = 'force-dynamic'

/**
 * Pushes the project to a REAL GitHub repository.
 * - Demo users: simulated push (no token available) so the preview works.
 * - Token users: real repo creation + real commit via GitHub REST API.
 */
export async function POST(_req: Request, ctx: { params: Promise<{ id: string }> }) {
  const user = await getSessionUser()
  if (!user) return NextResponse.json({ error: 'سجّل دخول أولاً' }, { status: 401 })

  const { id } = await ctx.params
  const project = await db.project.findFirst({
    where: { id, userId: user.id },
    include: { files: true },
  })
  if (!project) return NextResponse.json({ error: 'المشروع غير موجود' }, { status: 404 })
  if (!project.files.length) {
    return NextResponse.json({ error: 'ماكو ملفات للرفع بعد' }, { status: 400 })
  }

  // ── Real push (user logged in with a GitHub token) ─────────────────────
  if (user.accessToken) {
    try {
      const result = await pushProjectToGitHub(
        user.accessToken,
        user.username,
        project.name,
        project.description || `تطبيق ${project.appName} — generated by BuildAI`,
        project.files.map((f) => ({ path: f.path, content: f.content }))
      )

      const workflowUrl = `${result.htmlUrl}/actions`
      const commitSha = 'sha' + Math.random().toString(36).slice(2, 9)

      await db.project.update({
        where: { id: project.id },
        data: { status: 'pushed', githubUrl: result.htmlUrl, repoName: result.repoName },
      })

      const fakeLogs = [
        `[git] Creating repository ${result.repoName}...`,
        `[git] Repository created ✓ ${result.htmlUrl}`,
        `[git] Uploading ${project.files.length} files as blobs...`,
        `[git] Building tree & commit...`,
        `[git] Pushing to refs/heads/main ✓`,
        `[git] Commit: ${result.commitSha.slice(0, 7)} — Initial commit — generated by BuildAI 🤖`,
        ``,
        `✅ تم الرفع بنجاح! الـ workflow "Build APK" ساشتغل تلقائياً.`,
        `🔗 تابع الـ build من: ${workflowUrl}`,
      ].join('\n')

      return NextResponse.json({
        ok: true,
        real: true,
        commitSha,
        githubUrl: result.htmlUrl,
        workflowUrl,
        logs: fakeLogs,
      })
    } catch (err) {
      const message = err instanceof Error ? err.message : 'فشل الرفع ع GitHub'
      return NextResponse.json({ error: message }, { status: 502 })
    }
  }

  // ── Simulated push (demo session) ───────────────────────────────────────
  await new Promise((r) => setTimeout(r, 1200))
  const sha = Math.random().toString(16).slice(2, 9)
  const githubUrl = `https://github.com/${user.username}/${project.name}`
  const workflowUrl = `${githubUrl}/actions`

  await db.project.update({
    where: { id: project.id },
    data: { status: 'pushed', githubUrl, repoName: project.name },
  })

  const logs = [
    `[demo] 🎭 وضع تجريبي — ماكو توكن GitHub محفوظ`,
    `[git] Creating repository ${user.username}/${project.name}...`,
    `[git] Repository created ✓`,
    `[git] Uploading ${project.files.length} files...`,
    `[git] Commit ${sha} pushed to main ✓`,
    ``,
    `✅ (محاكاة) تم الرفع!`,
    `💡 سجّل دخول بالتوكن الحقيقي حتى يرفع فعلياً عحسابك.`,
  ].join('\n')

  return NextResponse.json({
    ok: true,
    real: false,
    commitSha: sha,
    githubUrl,
    workflowUrl,
    logs,
  })
}
